name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd hosting
          echo "REACT_APP_ENV=production" >> .env
          npm ci
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: hosting
          path: ./hosting/build
          retention-days: 1
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://crt.codesupport.dev
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: hosting
          path: ./hosting/build
      - run: npx firebase-tools deploy --token "${{ secrets.FIREBASE_TOKEN }}"
